site_name: Lorry's Docs
theme:
    name: 'material'
    language: 'zh'
    feature:
        tabs: true
markdown_extensions:
    - admonition
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.tasklist:
        custom_checkbox: true
nav:
    - 'Home': 'index.md'
    - '给程序员的7个编程建议': '7programming_suggestions.md'
    - '设计原则': 'code_principle.md'
    - '大数据': 
        - '大数据平台开发应知应会': bigdata_platform_dev.md
        - 'java 代码规范': bigdata_platform_dev/java_code_rule.md